server:
  port: 8761

spring:
  profiles:
    activate:
      on-profile: dev
  application:
    name: tgather
  cloud:
    config:
      uri: http://config-service:8888
      name: ecommerce
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
